server:
  servlet:
    context-path: /dev/asntomanhattan
  port: 8088

app:
  authUri: https://app.coppel.cloud/api/sso/v1/verify
  ignoreSession: true
  allowedOrigins: "*"
  allowedMethods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
  allowedHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Headers,Access-Control-Allow-Methods,Accept,Authorization,Content-Type,Method,Origin,X-Forwarded-For,X-Real-IP
  exposedHeaders: X-Get-Header
  environment: develop

  apiProxy:
  apiPort: 0
  maxAttempts: 3
  retryTimeInterval: 10000
  readTimeout: 1800000
  connectTimeout: 30000

  origenAccess: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiY3BsLW9tcy1kZXYtMTkwNTIwMjMiLAogICJwcml2YXRlX2tleV9pZCI6ICJjY2QzZTFmZDFiZWM1M2JkZTg1OGM5ZDk2MjUwZjhjZjNhZjczYTIzIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUUNpb2J6eGlvMUIyb1drXG52K0JnVnFQV3RYbWdWNWgvOWVRclBUa0hpYmxDeTFkMmM2YUZBYnA2eDdUejFpeExaQjAzRHFkV0VzOEwxNUNQXG5DaDFtN0grb0VTeXdmSFpFckNsVmZiVVpzTU54VE5MZUxYRGVPamtDQy9BOTVFQldxS0ZmUFVKNXlvekpKOExtXG5BQ0QvalQzbnV0dEFDZkhVT3lkZWg5V2Jma1pNV0RaSXN4cnRybGhIV1hPSmxKMWx4dmVEM3c5ZGYyeGE5MU5OXG5pcDN3dURscndySUtyVlN4YTFVU1h1NGF4ekhMSUpHeVBETTFhemdGdzhyakczQWFiNC93b3VWSHpEa1hQaklCXG5KMk91SVVwR3UvUUdWaHFabytKdGYwdndqV3VUS09wRlQ5eGpqSFNvaUY1VDR2VGllamlzVHdYdTlYd2VFUXZMXG5rQ0lBQ1NZakFnTUJBQUVDZ2dFQUV3L1ZCeFNmeU91MWhXRnVDYXl1Q0hEOTRBTFVYNDh4SHJaTzFHamFtNDhjXG40Y2ZkYVRLU0ttajA5eTJQeElobitqZVArb0U2M2w3MlZTV3cyNHIxelh1eDJyL0Qxdm04NElYYTc3ZHR1UDV4XG5xdFAxcWo1MXh4MGlIQWNBV1lmclhpL2Vka3I4NUdqeUthWXpOL0RVcERBZEdhend1TmowSE5yYitSMDhYUjg3XG43RW5DRnRTVXBRQ3IvWDdVd0VDb1NJb3FaZkczVkF1V0hrKzRTSElSR1ZsblpBMUNNQXhzOTV4bVJBM0RKb1gyXG4rN0JDZmNkdmFBeHRnVkl6UXc0alhBRE5BamtvdTNWZW5OdXBMbVlvenNHVjVBSmh5WXp0VjBZdzE2cCtSNmhnXG5heVZwRlN4M3E0YnRyS1puaEJyWkpFSVdPSzRZb2hHZ203MktaL1pwa1FLQmdRRE5nN3JpSHR1ZDQ4M0M5dFdjXG5XNzJ6TUMwdWk1VTBzY1RVS2ZVYXgzVTE4ZlBiSmdKaForY3FnSjFDM1QrL3d0WEh2WVVzYk94WmFBeWRZT0ZIXG5Fa3NHWVdHKzVrQTRodWNPVVhUK3N3bmtLNGNnM2JWa1FCQkxSdHhQMlZtTkFFRHdBM3cwVzhQUXZrMzVGWWcxXG53VVpUY28yQTVRN2Fia3lrWFRER1hPRkZzUUtCZ1FES2xUa1FObjlMa3dyaHZjc3RRdGhHZUU1WmhxMEE3ZmhSXG50OHMzSXg0ejNvRS9IOVdtazBQSFFST2o3VG9uV3FmU0RKb28wME01blpJektuekxaRDZtMldKNThuOE9ZL3FmXG5LOWpKSUQxTkhTMGEweXN4S1Zod1hsTWhPTE9ZcGk0MkdEMllQMUk4UEVKQS8zOVp2OHI5czF1ZnBDa0NHSGl0XG4rTVlaaEUwYUV3S0JnQUNTNkpldkRGL3hmZWFZZDlvNjYxbXZ2Y0NPaFRramNmQkJ1Yng4YUJoaGQ1UGFGRkdmXG5UNmJ2dXdDdnkzakdtNEEyU0VQcWZmSjE5dXNObFROMG1wOEc4Slh1NEtrSHYyZHIxTTdOUXk3TzdFNnNMOUI2XG4yVkRNZnRyK09XREthbVFCTG55YThQNEpPZ0NERGVGUWk5aTV6aWxZK21TandEVUpTWlNVTjlEUkFvR0FQVTh2XG45K0ltWUQ3ZUdqZVFWK0JWQis2ODk0YzBzSVZVazVhbUg4ZTNDa2Vhb2ZvR2RPVTRyQUxiNk02UXZQeElzZDh5XG5nSXgvV2Q2QU1vLzNPSzdiN3k3M0NLVUZJdHZMSzRUZmxPNzIzbkdvQnVoRnVCa2xOTXkzSitTN0pjV1ZVclcvXG5YbVk3Z3hOUmtjNUJRbTR6QnRqVEw5dEV0ZWVtRGpDdDgyY0ExcFVDZ1lBSUp1YXZRZlR4ZTNHM2kzTEZqWXBMXG5TU2dhazVnemkxVnVGb1BHZzNSc2VibTBGamkzcE0wRjJISFdoMnZpcG4ycWlwQmNMSE8yNlVJcmJTYkVValFpXG44b1RPMitRNjdqSDRSR1RoTURXWXQrMW9QcGRiRzJVV2prT0VZR09wcEtTRUVvTFhqcmJmQm9SNHVmZmxoN1IzXG45S1o2YncxK205MXdweGVtK1hESlR3PT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJna2UtaW52ZW50b3J5LWNvcmVAY3BsLW9tcy1kZXYtMTkwNTIwMjMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA4NTA0NTA1OTAxOTMwOTc0MTU1IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9na2UtaW52ZW50b3J5LWNvcmUlNDBjcGwtb21zLWRldi0xOTA1MjAyMy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgInVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSIKfQ==
  projectIdOrigen: cpl-oms-dev-19052023
  topicIdOrigen: prueba_esquema
  subIdOrigen: prueba_esquema-sub
  subIdOrigenSecond: spikeorder-sub

  desAccess: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiY3BsLW9tcy1kZXYtMTkwNTIwMjMiLAogICJwcml2YXRlX2tleV9pZCI6ICJjY2QzZTFmZDFiZWM1M2JkZTg1OGM5ZDk2MjUwZjhjZjNhZjczYTIzIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUUNpb2J6eGlvMUIyb1drXG52K0JnVnFQV3RYbWdWNWgvOWVRclBUa0hpYmxDeTFkMmM2YUZBYnA2eDdUejFpeExaQjAzRHFkV0VzOEwxNUNQXG5DaDFtN0grb0VTeXdmSFpFckNsVmZiVVpzTU54VE5MZUxYRGVPamtDQy9BOTVFQldxS0ZmUFVKNXlvekpKOExtXG5BQ0QvalQzbnV0dEFDZkhVT3lkZWg5V2Jma1pNV0RaSXN4cnRybGhIV1hPSmxKMWx4dmVEM3c5ZGYyeGE5MU5OXG5pcDN3dURscndySUtyVlN4YTFVU1h1NGF4ekhMSUpHeVBETTFhemdGdzhyakczQWFiNC93b3VWSHpEa1hQaklCXG5KMk91SVVwR3UvUUdWaHFabytKdGYwdndqV3VUS09wRlQ5eGpqSFNvaUY1VDR2VGllamlzVHdYdTlYd2VFUXZMXG5rQ0lBQ1NZakFnTUJBQUVDZ2dFQUV3L1ZCeFNmeU91MWhXRnVDYXl1Q0hEOTRBTFVYNDh4SHJaTzFHamFtNDhjXG40Y2ZkYVRLU0ttajA5eTJQeElobitqZVArb0U2M2w3MlZTV3cyNHIxelh1eDJyL0Qxdm04NElYYTc3ZHR1UDV4XG5xdFAxcWo1MXh4MGlIQWNBV1lmclhpL2Vka3I4NUdqeUthWXpOL0RVcERBZEdhend1TmowSE5yYitSMDhYUjg3XG43RW5DRnRTVXBRQ3IvWDdVd0VDb1NJb3FaZkczVkF1V0hrKzRTSElSR1ZsblpBMUNNQXhzOTV4bVJBM0RKb1gyXG4rN0JDZmNkdmFBeHRnVkl6UXc0alhBRE5BamtvdTNWZW5OdXBMbVlvenNHVjVBSmh5WXp0VjBZdzE2cCtSNmhnXG5heVZwRlN4M3E0YnRyS1puaEJyWkpFSVdPSzRZb2hHZ203MktaL1pwa1FLQmdRRE5nN3JpSHR1ZDQ4M0M5dFdjXG5XNzJ6TUMwdWk1VTBzY1RVS2ZVYXgzVTE4ZlBiSmdKaForY3FnSjFDM1QrL3d0WEh2WVVzYk94WmFBeWRZT0ZIXG5Fa3NHWVdHKzVrQTRodWNPVVhUK3N3bmtLNGNnM2JWa1FCQkxSdHhQMlZtTkFFRHdBM3cwVzhQUXZrMzVGWWcxXG53VVpUY28yQTVRN2Fia3lrWFRER1hPRkZzUUtCZ1FES2xUa1FObjlMa3dyaHZjc3RRdGhHZUU1WmhxMEE3ZmhSXG50OHMzSXg0ejNvRS9IOVdtazBQSFFST2o3VG9uV3FmU0RKb28wME01blpJektuekxaRDZtMldKNThuOE9ZL3FmXG5LOWpKSUQxTkhTMGEweXN4S1Zod1hsTWhPTE9ZcGk0MkdEMllQMUk4UEVKQS8zOVp2OHI5czF1ZnBDa0NHSGl0XG4rTVlaaEUwYUV3S0JnQUNTNkpldkRGL3hmZWFZZDlvNjYxbXZ2Y0NPaFRramNmQkJ1Yng4YUJoaGQ1UGFGRkdmXG5UNmJ2dXdDdnkzakdtNEEyU0VQcWZmSjE5dXNObFROMG1wOEc4Slh1NEtrSHYyZHIxTTdOUXk3TzdFNnNMOUI2XG4yVkRNZnRyK09XREthbVFCTG55YThQNEpPZ0NERGVGUWk5aTV6aWxZK21TandEVUpTWlNVTjlEUkFvR0FQVTh2XG45K0ltWUQ3ZUdqZVFWK0JWQis2ODk0YzBzSVZVazVhbUg4ZTNDa2Vhb2ZvR2RPVTRyQUxiNk02UXZQeElzZDh5XG5nSXgvV2Q2QU1vLzNPSzdiN3k3M0NLVUZJdHZMSzRUZmxPNzIzbkdvQnVoRnVCa2xOTXkzSitTN0pjV1ZVclcvXG5YbVk3Z3hOUmtjNUJRbTR6QnRqVEw5dEV0ZWVtRGpDdDgyY0ExcFVDZ1lBSUp1YXZRZlR4ZTNHM2kzTEZqWXBMXG5TU2dhazVnemkxVnVGb1BHZzNSc2VibTBGamkzcE0wRjJISFdoMnZpcG4ycWlwQmNMSE8yNlVJcmJTYkVValFpXG44b1RPMitRNjdqSDRSR1RoTURXWXQrMW9QcGRiRzJVV2prT0VZR09wcEtTRUVvTFhqcmJmQm9SNHVmZmxoN1IzXG45S1o2YncxK205MXdweGVtK1hESlR3PT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJna2UtaW52ZW50b3J5LWNvcmVAY3BsLW9tcy1kZXYtMTkwNTIwMjMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA4NTA0NTA1OTAxOTMwOTc0MTU1IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9na2UtaW52ZW50b3J5LWNvcmUlNDBjcGwtb21zLWRldi0xOTA1MjAyMy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgInVuaXZlcnNlX2RvbWFpbiI6ICJnb29nbGVhcGlzLmNvbSIKfQ==
  projectIdDes: cpl-oms-dev-19052023
  topicIdDes: dfHCJ
  subIdDes: prueba_esquema-sub

  urlAuthServiceManhattan: 'https://copps-auth.sce.manh.com/oauth/token?grant_type=password&username=kolea@texcoco&password=-0390Kboo'
  tokenAuthServiceManhattan: b21uaWNvbXBvbmVudC4xLjAuMDpiNHM4cmdUeWc1NVhZTnVu
  urlServicePurchaseOrderManhattan: https://copps.sce.manh.com/receiving/api/receiving/purchaseOrder/?query=PurchaseOrderId=
  urlMerchandising: https://copps.sce.manh.com/item-master/api/item-master/item/search
  urlServiceRestManhattan: https://copps.sce.manh.com/receiving/api/receiving/asn/bulkImport



spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/asn?currentSchema=public&ApplicationName=wms-sys-asn&socketTimeout=30
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    test-on-borrow: true
    test-while-idle: true
    validation-query: SELECT 1;
    time-between-eviction-runs-millis: 60000
    remove-abandoned: true
    remove-abandoned-timeout: 60
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    hikari:
      minimumIdle: 8
      maximumPoolSize: 14
      idleTimeout: 600000
      poolName: SpringBootJPAHikariInventory
      maxLifetime: 1800000
      connectionTimeout: 30000
      validationTimeout: 300000
# Conexion a bodega
bodega:
  datasource:
    #jdbc-url: jdbc:postgresql://localhost:5432/bodega?currentSchema=public&ApplicationName=di-convert-asntomanhatan&socketTimeout=30
    jdbc-url: jdbc:postgresql://localhost:5432/bodega?currentSchema=public&ApplicationName=di-convert-asntomanhatan&socketTimeout=30
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    hikari:
      minimumIdle: 4
      maximumPoolSize: 8
      idleTimeout: 15000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 1800000
      connectionTimeout: 30000

  sql:
    init:
      encoding: UTF-8

  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      format_sql: true

management:
  endpoint:
    health:
      group:
        custom:
          show-details: always
          show-components: always
    web:
      exposure:
        include: "*"
ws:
  wms:
    wms-sys-original-order:
      url: http://localhost:8080/dev/originalorder
      paths:
        root: /v1/completeorder