server:
  servlet:
    context-path: /dev/asntomanhattan
  port: 8088

app:
  authUri: https://app.coppel.cloud/api/sso/v1/verify
  ignoreSession: true
  allowedOrigins: "*"
  allowedMethods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
  allowedHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Headers,Access-Control-Allow-Methods,Accept,Authorization,Content-Type,Method,Origin,X-Forwarded-For,X-Real-IP
  exposedHeaders: X-Get-Header
  environment: develop

  origenAccess: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiY3BsLWNzLXdtcy1kZXYtMzAxMTIwMjMiLAogICJwcml2YXRlX2tleV9pZCI6ICI2N2U5MzFmM2UzMjdkZTY3OTI5M2JiZjQ5ODRhYjM4OGVlMTBkOTQxIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUUN2UWdVdlJYdHBnN2pzXG55UDA1UmZIOXdLZk5qVzYxdVJKOFVYZ3A2RlQ0U1pWb0xrRlFaeEZxQlpLMHIrZUNYMVdvdXpyRUJwa1RVMjdqXG53aXpGa0pwVFNTN2cwTnpFUjNORXJIUGZFMjloeGZ6L2tpK2NmSkFzdWlrVkpSSlpTbVdqRmEzWHhrWjZJbHplXG5nVHZkbEJJV3JLK0h0cjNJK285MVI2c0srNzdZMVBUS0FUQU1nTzdyc0NDeGthZk1TMGc0dDBaVHJlV3ZXK2ErXG5McDFpT0JFQXRWVDdhdFg3cDR4bkZKNDY4cllRQnN3V0RpUURPQnE1UkFtNkRNdngwTXRCK3oyVlUvdlFIaVJFXG5OdGZ1djFUOWZlV2ZDWXp3S1lGN29MSVhMeGFMUGNUWldNdm8ybUxSd056TGhYVHRBWXF6TjhkY0J4V2VHRyszXG5LcXVHek1OL0FnTUJBQUVDZ2dFQUVWenU2dVdDaExiR1J6M2h0SW02U3FPMUhEZG9ZZnhCYnNGRmhlVmMwYkpuXG5Qbk00Q1B3RkYzdG1NdklySGdQNFFSSU01WkhWR3VYaVdtY3pqS2szQTR4VnZCNkZMZ21rSVFnZGZMQWpaMHpqXG5DVkRxMkV2bVNXckhiNFJhTjlyQ2pMQ0tVTDBnaTF0dkxFNGlaN2FTbE40cjVSRlU1bk5JYTRhYnFxZ1JSWHI5XG5aVWcvUWtQcENYb2NZWWx5UDFFVU9rTGs5dmFyK0Y1VGF0N0dDR0hIT0oycmVoTFYzODlxNUN5UlkyQWQ4dTI2XG5YZHp6b2c0bkhWV2xJMVRLc01NU3BvcEdmV2NIMjNmUDhONk40MU1yRUxyWDNYcE5iMkNwYUZjdWozbndFQ25yXG4yZEJLWTMzdy9rVEZwblpFNU9NcDFUM2hLSGxxN0JROExPR1UySGNMNFFLQmdRRHQ0eHZxcFNHZ3lxWHFYd2M3XG54Ti9ZcU9iZXlQYTh4UEFPU2hyeEZpajExdDlrcFlXMnNvdk44aXN1R2NxSG9OVnNwdkJTL1pKcWhqT05ReVQyXG5NNS9sQkl0NVg1T1RybE5pcXJibnNJOU9DZ21LMEIvczlUdzZ6Q3h5WDJzUVlYQWUzRmhZTDBNd0llSnU1QW1lXG40anVCQ3l0aGVCSUFGRkF5bUcvMk9tc3o0UUtCZ1FDOG1pU29IanVyaE5pa3Y0TjhEWDNyVTRZUzE4Q29kUmtQXG53YmtTTkx6NUxJd2g0V1lqdU5sbDlPeGZlUy9BZm5BZnhHbkVya2gwTUw5ajZJVTVkRmFoQWFJNFZxQ1NUT1ppXG53dVpCNElFV3pHeWZnVysxeStsZjUvYlRVdU9YWGNvMFZZbmROZEp6MGdyazdhdXBWbTFmL3BxN0ZLS0orREFSXG50SU5aU29Ualh3S0JnQ3c4am1Wcy9icmoxRVNvRlRWRklBY3ZLWGVHVVhPNi81VDRyTmZtTWdtOVFsOTU5RXFNXG5HemxaN2pPdGNoOFVobnVrODQzTFA1MzFoTUtoR005N3ZDRWZYanhjekptcTBqREg1Q2xqaU5LUFJVVDkvT0hZXG5uTEdtWkNHRW91a3g1V0tud1BudEdBWnNWcW9lVjdlbkJEK3o3d1k2Q01iaEFDVFllZ0dFellpaEFvR0FYZ0FWXG50UlVjZUdoRjhoYmgyYnAvd0FKcEdJc2dJdFg2SDdoV0haVGJldldSQW5IdERuRGJLYzNnNGRUc3ordzB4aUNHXG45dGhHbEdLWGdad3FpbkJKblFYTGJIa0FudXBsQ1dSS2p4cnVQQWEzUE9pdVhOVzlBMmdCeFdIU3ZXYXBtVnZvXG4wckE0ckRGTDdMM29pUVhpamEzQVFPNFA5T1FXVVR5L0dvbmhvZEVDZ1lBTnQwakM5MHNWdk1WZmJGSm16Zi9SXG54UXR3WVFjWkE3dmNrbHJlVVRhcWVvSHlLVmNqNVpDUlNmOFltcmU1VGlzM1J2ZmpKdFdoWXhGTGovU0VxV09OXG5LNm1VODBsb004ZG0wcENiejIxSlJqNlRxRG9seERvV2dqYVBCNm1ja2ZTVDQ3UGJIVUY3UmRUbG04Rnc4KythXG40WW1CZVgvZ21EQlpmR0J0TGZKZ3VnPT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJzYS1na2UtaW52ZW50b3J5LWNvcmUtd21zLWRldkBjcGwtY3Mtd21zLWRldi0zMDExMjAyMy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMTM0OTkxNzU2NDQ4NjA3MjE3NTkiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L3NhLWdrZS1pbnZlbnRvcnktY29yZS13bXMtZGV2JTQwY3BsLWNzLXdtcy1kZXYtMzAxMTIwMjMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K
  projectIdOrigen: cpl-cs-wms-dev-30112023
  topicIdOrigen: u
  subIdOrigen: asnCreated-sub

  desAccess: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiY29wcC1tYXNjLXN0Zy0wMS1vcHMiLAogICJwcml2YXRlX2tleV9pZCI6ICIxMjY4ZTBkNjcyMDk1ZmIwMjkwOTJiODIyNDM4ODkzOTEzYTY2ZDk2IiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUURuWlYrbFF6UGFEMWlBXG53dU5SNk5ua3FsaDRHWnkweG9XQlZIT0Z6aWRVUGEwNEtmc1dwMmF4M2x0VVpLM0dhR3N1WTM0WjUydXJwRXRUXG51UEVna2pOMWpXZGhKanlsNkh6Tk5LaXRISlBWK2dHZlZOWFFIZHM0WUlHNUhNT2k2WUFEYk5PNjNua1hpcVh4XG44NGhmbTdYYWlTeWRoUEtzUTI4WnZOUUcvRFlTZlNDOHZiYVE2Vzc0RmdlbFVZQUdUYkRyUC9FdXUwZnpPd0VyXG5CUWd1dVo0WHBmNFdCWTVqS1hTTllCY0FjcEZjTXhnTXQ0N0tySTlUY0lPd3d1T3ZkV09DMkNTbzdTQnJBdjJwXG5PbkNZUmtiOHVPZm1WN2R3UW5oaFFCSTFpRktYalJvMWR1ZkJ6UmZaaWl1THBIM3NhNmk0NCswMXFHbURiWTVsXG5OcGs1aklvVkFnTUJBQUVDZ2dFQURwUWJkNDBKV2thM083MkxsdUNGd2R0ZG9ZdHpqUXdvNHlJUCtURW8xeXpmXG5tZmRESTRVK2VoeFpRckxwSStQMlJNRHQ4L0habmNISElTbzR2dVdYS21QVFRKS2RKWkxGTWlTTU1BUHA2SVJNXG56OTRIYm9wREFvVktCd0NoN3NTcFZRM3BOUS9KTDB1RDh2OTE2eGdqVi9abWdqSWJHL0ZQc1o1cytWZXdqRytKXG5FSTNVNys2cm5FclJWZkpQVEw1N21va3MxWm5MeVgvalNnVnVmQk0yaW5HM3pYckI4T2g2cTV0ODBsL2lEMldkXG5uVnV1OFlCYXkzK1JidHRQcXFRY3hNSjR5SUgxSlU1T2lRNURRMXl6clRtdVZJL3FBdXJJZ2FEeTFYRlJOZ01JXG42c1lyUUlCekw2ZDJVYnh3N3UzMDFNVW1oSUdpandiS0R3blIwZVREWVFLQmdRRDRvaU45dnQ2MVkrZmEwWEtzXG5JQ2dKUkg0d01EanJsNjBaZXd2ZHFNOGVTYXZUWmJhY1k5UW45QTF1blZQL2hhUTNCc3pXdTRhaGVDL0QxRnIzXG5kaFRCbEJEaVR1MXQ4Mk45MnZtd3lJRytaWWNVUDVXYm5pZkxLM040allrVXlYUzQ4aTgwS2g1d3F6aTRDSlg3XG5oQ1RxM3RwL1U3MWNZRmFneVdxMWhHMnNpUUtCZ1FEdVFIMjd0OWNMZTltQmFUQ0hjdmF5N3kvbjRlTk9OQVNtXG5LSlRoUk9Wd1kwSWlUbS9YYTM5OFZYd01KNDRrd3d4T0pVVkljbVI0SUd4SExvS3NyVFZFME9FVWFSUzhubmdqXG5oc2RsQVE5dGdEdDI0ak9ZazM4WFZGWldMT3F0d2UyS3dNT0R6NEJMeVNlNS9vTzErQUFUYmVpOHROV1lXV0ZpXG5yUm9raytvR0xRS0JnR3VMMXNaQmxadm9oeFhEbTFLUTVrQjcvQWxrRW5yMXRNNWN4eGt1TjhqbUhRam42a0ZqXG5mUlY3SDRSRlVWd3B0b3FHeW52bnlhaDJrRktvdkdCbUZ6eFVpNmtZY3VNb2NGUzBMMlVrbGRxQm1CaE9HS3lqXG5rSnIxUkpGVXg0TFNVVWJlbTBSNUk0bWd4bnYwV3N2Y3NRdFhNalA1U09ONFdJQmNIMmc4ekNQaEFvR0FDUE5IXG5SZXdNR2hSWEFYT1FMU1oyZWhaZU9GbldEalFLRUt2cG0rVFlzYllvMzkwT2VvdEJTTXgxVW9lUjRYT3FYSzB0XG53eUQ1QVVKR2p3NENQclpyRCtEQTgrRld0QmRIOEIyNkUrTk1UeExJS1JrcVV3c0hkVHJuMjJqb2tBcCsvLzFwXG4ydVBLc0E0b2ZlWS8wSEEyb0lRNmdBeFRFZHdadW5sQ1NDbCtXeWtDZ1lFQTlVM1Y5aStodzRCaklKVFc2RWcyXG5mN1RnOHgyKzB5V1hzRHBHcHpMNEJIWFc0THRSMWlNUExuTzhmVFkrOHZNTjMvQm5TK1dMd2lTbGtrek9LcFBYXG5UZE1YOFFwQ2UwR09lcE1QYURMWUhOT2pMdVViQ05YRkgvcFBuYmQ2UFo5bnE0b2ZNZVI2SnZNUGg2WEF0MDVTXG54bDRkOHVnZzZIMHpabVBoaDh5VVh0cz1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJjb3Bwc3NmMTFvLXB1YnN1YnJ3QGNvcHAtbWFzYy1zdGctMDEtb3BzLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAiY2xpZW50X2lkIjogIjEwMzQzMzYzNjA2MTgyNDA5NDI1MiIsCiAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwKICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwKICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsCiAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvY29wcHNzZjExby1wdWJzdWJydyU0MGNvcHAtbWFzYy1zdGctMDEtb3BzLmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9Cgo=
  projectIdDes: copp-masc-stg-01-ops
  topicIdDes: COPP_INB_HST_XINT_ASN_GCPQ
  subIdDes: q

  urlAuthServiceManhattan: https://copps-auth.sce.manh.com/oauth/token?grant_type=password&username=kolea@texcoco&password=0390-Kboo
  tokenAuthServiceManhattan: b21uaWNvbXBvbmVudC4xLjAuMDpiNHM4cmdUeWc1NVhZTnVu
  urlServicePurchaseOrderManhattan: https://copps.sce.manh.com/receiving/api/receiving/purchaseOrder/?query=PurchaseOrderId=
  urlMerchandising: https://copps.sce.manh.com/item-master/api/item-master/item/search


spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5433/asn?currentSchema=public&ApplicationName=wms-sys-asn&socketTimeout=30
    driver-class-name: org.postgresql.Driver
    username: syswmsasn
    password: "##PLMnjii98!$"
    test-on-borrow: true
    test-while-idle: true
    validation-query: SELECT 1;
    time-between-eviction-runs-millis: 60000
    remove-abandoned: true
    remove-abandoned-timeout: 60
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    hikari:
      minimumIdle: 8
      maximumPoolSize: 14
      idleTimeout: 600000
      poolName: SpringBootJPAHikariInventory
      maxLifetime: 1800000
      connectionTimeout: 30000
      validationTimeout: 300000
# Conexion a bodega
bodega:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5433/bodega?currentSchema=public&ApplicationName=di-convert-asntomanhatan&socketTimeout=30
    driver-class-name: org.postgresql.Driver
    username: syswmsasn
    password: "##PLMnjii98!$"
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    hikari:
      minimumIdle: 4
      maximumPoolSize: 8
      idleTimeout: 15000
      poolName: SpringBootJPAHikariCP
      maxLifetime: 1800000
      connectionTimeout: 30000

  sql:
    init:
      encoding: UTF-8

  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      format_sql: true

management:
  endpoint:
    health:
      group:
        custom:
          show-details: always
          show-components: always
    web:
      exposure:
        include: "*"
ws:
  wms:
     wms-sys-original-order:
      url: http://localhost:8080/dev/originalorder
      paths:
        root: /v1/completeorder